application:
  subdomain: thinkread
  upstreams:
    - location: /
      backend: http://thinkread:8080/

services:
  thinkread:
    # upstream: nikunjsingh/thinkread-ebook-reader:v1.3.0
    image: nikunjsingh/thinkread-ebook-reader:v1.3.0
    environment:
      - DATA_DIR=/data
    binds:
      - /lzcapp/var/data:/data
