application:
  subdomain: thinkread
  upstreams:
    - location: /
      backend: http://thinkread:8080/
services:
  thinkread:
    # upstream: nikunjsingh/thinkread-ebook-reader:v1.3.1
    image: registry.lazycat.cloud/czyt/nikunjsingh/thinkread-ebook-reader:be9170db3e1ada7f
    environment:
      - DATA_DIR=/data
    binds:
      - /lzcapp/var/data:/data
